version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  api:
    build: ./back
    container_name: cdn-api
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/cdnproject?authSource=admin
      JWT_SECRET: your_secret_key
    ports:
      - "8081:8081"
    networks:
      - app-network

  front:
    build: ./front
    container_name: cdn-front
    restart: always
    depends_on:
      - api
    environment:
      VITE_API_URL: http://localhost:8081
    ports:
      - "80:80"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
